version: '3'

services:
  app:
    build: '.'
    depends_on:
      - db
    networks:
      - common_nw
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - 8080:8080
  db:
    image: postgres
    container_name: connie_demo_db_1
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    networks:
      - common_nw

networks:
  common_nw:
